# Використовуємо вертикальний поділ (зліва і справа)
layout tall:bias=35

# 1. Відкриваємо ліве вікно. Воно виведе картинку і просто чекатиме (щоб не закритись)
launch bash -c "~/.config/kitty/draw_art.sh"

# 2. Відкриваємо праве вікно (твоя робоча оболонка, наприклад zsh або bash)
launch zsh

# Робимо праве вікно активним за замовчуванням, щоб ти міг одразу вводити команди
focus
